apiVersion: v1  # Menunjukkan versi API Kubernetes yang digunakan dalam konfigurasi.
kind: Service # Menunjukkan bahwa ini adalah konfigurasi untuk objek "Service" dalam Kubernetes.
metadata: # Mendefinisikan metadata terkait dengan layanan, seperti nama dan label.
  name: karsajobs-ui-service # service name
  labels:
    app: karsajobs-ui
    type: frontend
spec:
  type: NodePort # Menentukan tipe layanan, yang dalam hal ini adalah "NodePort." Ini berarti layanan akan diakses melalui port yang ditentukan di semua node Kubernetes.
  selector: # Menentukan kriteria pemilihan pod yang akan diarahkan oleh layanan ini. Dalam hal ini, pod dengan label "app: karsajobs-ui" dan "type: frontend" akan diarahkan oleh layanan ini.
    app: karsajobs-ui
    type: frontend
  ports:  # Mendefinisikan konfigurasi port untuk layanan.
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - protocol: TCP # Menentukan bahwa protokol yang digunakan adalah TCP.
      port: 8000  # Menentukan port yang akan digunakan oleh layanan.
      targetPort: 8000  # Menentukan port target pada pod yang akan menerima lalu lintas dari layanan. Dalam hal ini, sama dengan port layanan.
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30011 # Menentukan port yang akan dialokasikan secara khusus di setiap node Kubernetes untuk menerima lalu lintas yang ditujukan ke layanan ini.