apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service # service name
  labels:
    app: karsajobs-ui
    type: frontend
spec:
  type: NodePort # using node port
  selector:
    app: karsajobs-ui
    type: frontend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30011